import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler, RobustScaler

class CMapssPreprocessor(BaseEstimator, TransformerMixin):
    def __init__(self):
        # 1. Define the strict output order of the 24 features you requested
        self.features_settings = ['setting_1', 'setting_2', 'setting_3']
        self.features_sensors = [f'sensor_{i}' for i in range(1, 22)]
        self.correct_order_ = self.features_settings + self.features_sensors

        # 2. Lists of sensors grouped by their scaling strategy
        self.features_minmax = [
            'sensor_1', 'sensor_2', 'sensor_3', 'sensor_4', 'sensor_5',
            'sensor_6', 'sensor_7', 'sensor_9', 'sensor_10', 'sensor_11',
            'sensor_12', 'sensor_16', 'sensor_17', 'sensor_20', 'sensor_21'
        ]

        self.features_robust = [
            'sensor_8', 'sensor_13', 'sensor_14', 'sensor_15', 'sensor_18', 'sensor_19'
        ]

        # 3. Build the internal ColumnTransformer
        self.scaling_pipeline = ColumnTransformer(
            transformers=[
                ('num_minmax', Pipeline([
                    ('imputer', SimpleImputer(strategy='median')),
                    ('scaler_minmax', MinMaxScaler())
                ]), self.features_minmax),

                ('num_robust', Pipeline([
                    ('imputer', SimpleImputer(strategy='median')),
                    ('scaler_robust', RobustScaler())
                ]), self.features_robust)
            ],
            remainder='passthrough'  # Lets the settings pass through untouched
        )

    def fit(self, X, y=None):
        # The pipeline learns statistics (min, max, medians) ONLY from X_train
        # We ensure it reads the columns in the expected order
        X_input = X[self.correct_order_]
        self.scaling_pipeline.fit(X_input)
        return self

    def transform(self, X):
        # Force the input to match the correct column order
        X_input = X[self.correct_order_]

        # Transform (sklearn returns a shuffled NumPy array here)
        X_transformed_array = self.scaling_pipeline.transform(X_input)

        # Map the temporary order generated by sklearn's ColumnTransformer
        column_order_sklearn = self.features_minmax + self.features_robust + self.features_settings
        df_temporal = pd.DataFrame(X_transformed_array, columns=column_order_sklearn)

        # REORDER! Return the DataFrame with the 3 settings first and sensors 1 to 21 consecutively
        return df_temporal[self.correct_order_]
